gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.15
  expandFocusedSidePanel: true
  showIcons: true
refresher:
  refreshInterval: 1
git:
  paging:
    colorArg: always
    pager: delta --paging=never --true-color=auto --dark --side-by-side --line-numbers --syntax-theme=Dracula --width=variable --navigate
keybinding:
  universal:
    executeShellCommand: ";"
customCommands:
  - key: "<c-R>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
promptToReturnFromSubprocess: false
