gui:
  showIcons: true
git:
  refresher:
    refreshInterval: 1
keybinding:
  universal:
    executeCustomCommand: ";"
customCommands:
  - key: '<c-r>'
    context: 'commits'
    command: 'git push && gh pr create'
