gui:
  showIcons: true
git:
  refresher:
    refreshInterval: 1
keybinding:
  universal:
    executeCustomCommand: ";"
customCommands:
  - key: "<c-R>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
