return function()
  require('legendary').setup {
    keymaps = {
      -- Development
      { ',u',              ':<C-u>Lazy update<CR>',                                           mode = 'n', description = '[lazy.nvim] Update plugins', opts = { silent = true, remap = false } },
      { ',s',              ':<C-u>source %<CR>',                                              mode = 'n', description = '[neovim] Load vim config',   opts = { silent = true, remap = false } },
      { 'w',               '<Plug>CamelCaseMotion_w',                                         mode = '',  description = '[CamelCaseMotion] w',        opts = { silent = true, remap = true } },
      -- Enhanced move
      { 'b',               '<Plug>CamelCaseMotion_b',                                         mode = '',  description = '[CamelCaseMotion] b',        opts = { silent = true, remap = true } },
      { 'e',               '<Plug>CamelCaseMotion_e',                                         mode = '',  description = '[CamelCaseMotion] e',        opts = { silent = true, remap = true } },
      { 'ge',              '<Plug>CamelCaseMotion_ge',                                        mode = '',  description = '[CamelCaseMotion] ge',       opts = { silent = true, remap = true } },
      { '*',               "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>",       mode = 'n', description = '[hlslens] *',                opts = { silent = true, remap = true } },
      { '*',               "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>",       mode = 'v', description = '[hlslens] *',                opts = { silent = true, remap = true } },
      { '#',               "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>",       mode = 'n', description = '[hlslens] #',                opts = { silent = true, remap = true } },
      { '#',               "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>",       mode = 'v', description = '[hlslens] #',                opts = { silent = true, remap = true } },
      { 'g*',              "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>",      mode = 'n', description = '[hlslens] g*',               opts = { silent = true, remap = true } },
      { 'g*',              "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>",      mode = 'v', description = '[hlslens] g*',               opts = { silent = true, remap = true } },
      { 'g*',              "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>",      mode = 'v', description = '[hlslens] g*',               opts = { silent = true, remap = true } },
      { 'g#',              "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>",      mode = 'n', description = '[hlslens] g#',               opts = { silent = true, remap = true } },
      { 'g#',              "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>",      mode = 'v', description = '[hlslens] g#',               opts = { silent = true, remap = true } },
      -- <leader>
      { '<leader><space>', ':<C-u>HopChar1<CR>',                                              mode = '',  opts = { remap = false, silent = true } },
      { '<leader>a',       ':lua vim.lsp.buf.code_action()<CR>',                              mode = 'n', opts = { remap = false, silent = true } },
      { "<leader>b",       ":<C-u>Telescope file_browser<CR>",                                mode = "n", opts = { remap = false, silent = true } },
      { "<leader>B",       ":<C-u>Telescope file_browser path=%:p:h select_buffer=true<CR>",  mode = "n", opts = { remap = false, silent = true } },
      { '<leader>c',       ':<C-u>noh<CR>',                                                   mode = "n", opts = { remap = false, silent = true } },
      { '<leader>d',       ':lua vim.lsp.buf.definition()<CR>',                               mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>f',       ':<C-u>Telescope current_buffer_fuzzy_find<CR>',                   mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>F',       ':<C-u>Telescope live_grep<CR>',                                   mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>h',       '<cmd>lua require("spectre").open_file_search()<CR>',              mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>H',       '<cmd>lua require("spectre").open()<CR>',                          mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>i',       ':lua vim.lsp.buf.implementation()<CR>',                           mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>j',       ':lua vim.diagnostic.goto_next()<CR>',                             mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>k',       ':lua vim.diagnostic.goto_prev()<CR>',                             mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>l',       ':lua vim.lsp.buf.format { async = true }<CR>',                    mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>m',       '<cmd>lua require("renamer").rename()<cr>',                        mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>m',       '<cmd>lua require("renamer").rename()<cr>',                        mode = 'v', opts = { remap = false, silent = true } },
      { "<Leader>nf",      ":lua require('neogen').generate()<CR>",                           mode = "n", opts = { remap = false, silent = true } },
      { "<Leader>nc",      ":lua require('neogen').generate({ type = 'class' }}<CR>",         mode = "n", opts = { remap = false, silent = true } },
      { '<leader>r',       ':<C-u>Telescope lsp_references<CR>',                              mode = 'n', opts = { remap = false, silent = true } },
      { "<leader>sh",      ":<C-u>SidewaysLeft<CR>",                                          mode = "n", opts = { remap = false, silent = true } },
      { "<leader>sl",      ":<C-u>SidewaysRight<CR>",                                         mode = "n", opts = { remap = false, silent = true } },
      { '<leader>s',       '<Cmd>lua require"telescope.builtin".lsp_document_symbols{}<CR>',  mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>S',       '<Cmd>lua require"telescope.builtin".lsp_workspace_symbols{}<CR>', mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>t',       ':lua vim.lsp.buf.type_definition()<CR>',                          mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>v',       '<cmd>lua require("spectre").open_visual({select_word=true}<CR>',  mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>V',       '<cmd>lua require("spectre").open_visual({select_word=true}<CR>',  mode = 'v', opts = { remap = false, silent = true } },
      { '<leader>/',       '<Plug>(comment_toggle_linewise_current)',                         mode = 'n', opts = { remap = true, silent = true } },
      { '<leader>/',       '<Plug>(comment_toggle_blockwise_visual)',                         mode = 'v', opts = { remap = true, silent = true } },
      { '<leader>;',       ':<C-u>CommaOrSemiColon<CR>',                                      mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>,',       ':<C-u>SplitjoinSplit<CR>',                                        mode = 'n', opts = { remap = false, silent = true } },
      { '<leader>.',       ':<C-u>SplitjoinJoin<CR>',                                         mode = 'n', opts = { remap = false, silent = true } },
      -- <A->
      { '<A-a>',           ':<C-u>EasyAlign<CR>',                                             mode = 'n', opts = { remap = false, silent = false } },
      { '<A-a>',           ':<C-u>EasyAlign<CR>',                                             mode = 'v', opts = { remap = false, silent = false } },
      { '<A-b>',           ':<C-u>Telescope git_branches<CR>',                                mode = 'n', opts = { remap = false, silent = true } },
      { '<A-c>',           ':<C-u>Telescope commands<CR>',                                    mode = 'n', opts = { remap = false, silent = true } },
      { "<A-d>",           "<cmd>FloatermNew lazydocker<CR>",                                 mode = "n", opts = { remap = false, silent = true } },
      { '<A-e>',           ':<C-u>Telescope buffers<CR>',                                     mode = 'n', opts = { remap = false, silent = true } },
      { "<A-g>",           "<cmd>FloatermNew lazygit<CR>",                                    mode = "n", opts = { remap = false, silent = true } },
      { '<A-G>',           ":<C-u>GHInteractive<CR>",                                         mode = 'n', opts = { remap = false, silent = true } },
      { '<A-h>',           ':<C-u>Telescope command_history<CR>',                             mode = 'n', opts = { remap = false, silent = true } },
      { '<A-i>',           ':<C-u>Telescope diagnostics<CR>',                                 mode = 'n', opts = { remap = false, silent = true } },
      { "<A-j>",           ":m .+1<CR>==",                                                    mode = "n", opts = { remap = false, silent = true } },
      { "<A-j>",           ":m '>+1<CR>gv=gv",                                                mode = "v", opts = { remap = false, silent = true } },
      { "<A-k>",           ":m .-2<CR>==",                                                    mode = "n", opts = { remap = false, silent = true } },
      { "<A-k>",           ":m '<-2<CR>gv=gv",                                                mode = "v", opts = { remap = false, silent = true } },
      { '<A-l>',           ':<C-u>Octo actions<CR>',                                          mode = 'n', opts = { remap = false, silent = true } },
      { '<A-m>',           ':<C-u>Telescope marks<CR>',                                       mode = 'n', opts = { remap = false, silent = true } },
      { '<A-n>',           ':<C-u>bnext<CR>',                                                 mode = 'n', opts = { remap = false, silent = true } },
      { '<A-o>',           ':<C-u>Telescope find_files find_command=fd,-HLE.git,-tf<CR>',     mode = 'n', opts = { remap = false, silent = true } },
      { '<A-p>',           ':<C-u>bprev<CR>',                                                 mode = 'n', opts = { remap = false, silent = true } },
      { "<A-t>",           ":<C-u>NeoTreeFloatToggle<CR>",                                    mode = "n", opts = { remap = false, silent = true } },
      { '<A-w>',           ":<C-u>Bdelete<CR>",                                               mode = 'n', opts = { remap = false, silent = true } },
      { "<A-x>",           "<cmd>FloatermToggle<CR>",                                         mode = "n", opts = { remap = false, silent = true } },
      { "<A-x>",           "<cmd>FloatermToggle<CR>",                                         mode = "t", opts = { remap = false, silent = true } },
      { '<A-y>',           ':<C-u>Telescope registers<CR>',                                   mode = 'n', opts = { remap = false, silent = true } },
      { '<A-;>',           'g%',                                                              mode = 'n', opts = { remap = true, silent = true } },
      { '<A-;>',           'g%',                                                              mode = 'v', opts = { remap = true, silent = true } },
      -- Others
      { 'K',               ':lua vim.lsp.buf.hover()<CR>',                                    mode = 'n', description = '[Lsp] Hover description',    opts = { remap = false, silent = true } },
      { '<C-k>',           ':lua vim.lsp.buf.signature_help()<CR>',                           mode = 'n', description = '[Lsp] Show signature help',  opts = { remap = false, silent = true } },
    },
  }
end
