#! /bin/bash

if [ "`ps -eo pid,cmd | grep systemd | grep -v grep | sort -n -k 1 | awk 'NR==1 { print $1  }'`" != "1"  ]; then
      genie -s
fi
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
