let g:loaded_gzip = 1
let g:loaded_man = 1
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
let g:loaded_shada_plugin = 1
let g:loaded_tarPlugin = 1
let g:loaded_tar = 1
let g:loaded_zipPlugin = 1
let g:loaded_zip = 1
let g:loaded_netrwPlugin = 1

syntax on

colorscheme slate

set encoding=UTF-8
set cursorline
set scrolloff=8
set showmode
set hidden
set nobackup
set noswapfile
set noundofile
set splitright
set splitbelow
set hlsearch
set expandtab
set smartcase
set ignorecase
set autoindent
set smartindent
set pastetoggle=<C-b>
set tabstop=4
au FileType yaml setlocal sw=2 sts=2 ts=2 et

nnoremap <silent> <CR> :w<CR>
nnoremap q :q<CR>
nnoremap ; :
nnoremap m ;
nnoremap : m
nnoremap U <C-r>
nnoremap <C-y> <C-v>
nnoremap H ^
nnoremap L $
nnoremap j gj
nnoremap k gk
nnoremap <silent> z :<C-u>noh<CR>

