let g:loaded_gzip = 1
let g:loaded_man = 1
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
let g:loaded_shada_plugin = 1
let g:loaded_tarPlugin = 1
let g:loaded_tar = 1
let g:loaded_zipPlugin = 1
let g:loaded_zip = 1
let g:loaded_netrwPlugin = 1

syntax on

colorscheme slate

set encoding=UTF-8
set cursorline
set scrolloff=8
set showmode
set hidden
set nobackup
set noswapfile
set noundofile
set splitright
set splitbelow
set hlsearch
set expandtab
set smartcase
set ignorecase
set autoindent
set smartindent
set pastetoggle=<C-b>
set tabstop=4
set noerrorbells
set clipboard=unnamed

au InsertLeave * set nopaste
au FileType * set formatoptions-=cro
au FileType yaml setlocal sw=2 sts=2 ts=2 et
au BufReadPost * if line("'\"") > 0 && line ("'\"") <= line("$") | exe "normal g'\"" | endif

nnoremap <silent> <CR> :w<CR>
nnoremap q :q<CR>
nnoremap z :qa<CR>
nnoremap <silent> <C-q> :noh<CR>
nnoremap <C-y> <C-v>
nnoremap U <C-r>
nnoremap vy ggVG
nnoremap j gj
nnoremap k gk
nnoremap H ^
vnoremap H ^
vnoremap L $
nnoremap L $
nnoremap ; :
nnoremap : m
nnoremap m ;
vnoremap ; :
vnoremap : m
vnoremap m ;

