local set_keymap = vim.api.nvim_set_keymap

set_keymap('n', '<CR>', ':<C-u>w<CR>', { noremap = true, silent = true })
set_keymap('n', 'q', ':q<CR>', { noremap = true, silent = true })
set_keymap('n', 'Q', ':qa<CR>', { noremap = true, silent = true })
set_keymap('n', '<C-q>', 'q', { noremap = true, silent = true })
set_keymap('n', '<C-y>', '<C-v>', { noremap = true, silent = true })
set_keymap('n', 'U', '<C-r>', { noremap = true, silent = true })
set_keymap('n', 'vy', 'ggVG', { noremap = true, silent = true })
set_keymap('i', 'jj', '<Esc>', { noremap = true, silent = true })
set_keymap('n', 'j', 'gj', { noremap = true, silent = true })
set_keymap('n', 'k', 'gk', { noremap = true, silent = true })
set_keymap('n', 'H', '^', { noremap = true, silent = true })
set_keymap('n', 'L', '$', { noremap = true, silent = true })
set_keymap('v', 'H', '^', { noremap = true, silent = true })
set_keymap('v', 'L', '$', { noremap = true, silent = true })
set_keymap('n', ';', ':', { noremap = true, silent = false })
set_keymap('n', ':', 'm', { noremap = true, silent = true })
set_keymap('n', 'm', ';', { noremap = true, silent = true })
set_keymap('v', ';', ':', { noremap = true, silent = true })
set_keymap('v', ':', 'm', { noremap = true, silent = true })
set_keymap('v', 'm', ';', { noremap = true, silent = true })
set_keymap('n', 'R', '<Plug>(operator-replace)', { noremap = false, silent = true })
set_keymap('v', 'R', '<Plug>(operator-replace)', { noremap = false, silent = true })
set_keymap('', 'w', '<Plug>CamelCaseMotion_w', { noremap = false, silent = true })
set_keymap('', 'b', '<Plug>CamelCaseMotion_b', { noremap = false, silent = true })
set_keymap('', 'e', '<Plug>CamelCaseMotion_e', { noremap = false, silent = true })
set_keymap('', 'ge', '<Plug>CamelCaseMotion_ge', { noremap = false, silent = true })
set_keymap('n', '*', "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', '*', "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('n', '#', "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', '#', "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('n', 'g*', "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', 'g*', "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('n', 'g#', "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', 'g#', "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })

vim.g.mapleader = ' '
set_keymap('', ',', ':<C-u>HopChar1<CR>', { noremap = true, silent = true })
set_keymap('n', 'K', ':lua vim.lsp.buf.hover()<CR>', { noremap = true, silent = true })
set_keymap("n", "<C-x>", "<cmd>FloatermToggle<CR>", { noremap = true, silent = true })
set_keymap("t", "<C-x>", "<cmd>FloatermToggle<CR>", { noremap = true, silent = true })
set_keymap('n', '<C-k>', ':lua vim.lsp.buf.signature_help()<CR>', { noremap = true, silent = true })
set_keymap("n", "<C-g>", "<cmd>FloatermNew lazygit<CR>", { noremap = true, silent = true })
set_keymap('n', '<leader>a', ':lua vim.lsp.buf.code_action()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>c', ':<C-u>noh<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>d', ':lua vim.lsp.buf.definition()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>f', ':<C-u>Telescope current_buffer_fuzzy_find<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>F', ':<C-u>Telescope live_grep<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>G', ":<C-u>GHInteractive<CR>", { noremap = true, silent = true })
set_keymap('n', '<leader>h', '<cmd>lua require("spectre").open_file_search()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>H', '<cmd>lua require("spectre").open()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>i', ':lua vim.lsp.buf.implementation()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>j', ':lua vim.diagnostic.goto_next()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>k', ':lua vim.diagnostic.goto_prev()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>l', ':lua vim.lsp.buf.formatting()<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>m', '<cmd>lua require("renamer").rename()<cr>', { noremap = true, silent = true })
set_keymap('v', '<leader>m', '<cmd>lua require("renamer").rename()<cr>', { noremap = true, silent = true })
set_keymap('n', '<leader>r', ':lua vim.lsp.buf.references()<CR>', { noremap = true, silent = true })
-- set_keymap('n', '<leader>r', ':<C-u>Telescope lsp_references<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>s', '<Cmd>lua require"telescope.builtin".lsp_document_symbols{}<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>S', '<Cmd>lua require"telescope.builtin".lsp_workspace_symbols{}<CR>', { noremap = true, silent = true })
set_keymap('n', '<leader>t', ':lua vim.lsp.buf.type_definition()<CR>', { noremap = true, silent = true })

set_keymap('n', 'ta', '<Plug>(EasyAlign)', { noremap = false, silent = false })
set_keymap('x', 'ta', '<Plug>(EasyAlign)', { noremap = false, silent = false })
set_keymap('n', 'tb', ':<C-u>Telescope git_branches<CR>', { noremap = true, silent = true })
set_keymap('n', 'td', ':<C-u>DiffviewOpen<CR>', { noremap = true, silent = true })
set_keymap('n', 'tD', ':<C-u>DiffviewClose<CR>', { noremap = true, silent = true })
set_keymap('n', 'te', ':<C-u>Telescope buffers<CR>', { noremap = true, silent = true })
set_keymap('n', 'tg', ':<C-u>Octo actions<CR>', { noremap = true, silent = true })
set_keymap('n', 'th', ':<C-u>Telescope command_history<CR>', { noremap = true, silent = true })
set_keymap('n', 'ti', ':<C-u>Telescope diagnostics<CR>', { noremap = true, silent = true })
set_keymap('n', 'tk', ':<C-u>Telescope commands<CR>', { noremap = true, silent = true })
set_keymap('n', 'tm', ':<C-u>Telescope marks<CR>', { noremap = true, silent = true })
set_keymap('n', 'tn', ':<C-u>bnext<CR>', { noremap = true, silent = true })
set_keymap('n', 'to', ':<C-u>Telescope find_files find_command=fd,-HLE.git,-tf<CR>', { noremap = true, silent = true })
set_keymap('n', 'tp', ':<C-u>bprev<CR>', { noremap = true, silent = true })
set_keymap('n', 'tt', ':<C-u>NeoTreeFloatToggle<CR>', { noremap = true, silent = true })
set_keymap('n', 'tw', ":<C-u>Bdelete<CR>", { noremap = true, silent = true })
set_keymap('n', 'ty', ':<C-u>Telescope registers<CR>', { noremap = true, silent = true })
set_keymap('n', 't;', ':<C-u>CommaOrSemiColon<CR>', { noremap = true, silent = true });
set_keymap('n', 't?', ':<C-u>Telescope keymaps<CR>', { noremap = true, silent = true })
set_keymap('n', 't*', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>',
    { noremap = true, silent = true })
set_keymap('v', 't*', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>',
    { noremap = true, silent = true })
set_keymap('n', 't/', '<Plug>(comment_toggle_linewise_current)', { noremap = false, silent = true })
set_keymap('v', 't/', '<Plug>(comment_toggle_blockwise_visual)', { noremap = false, silent = true })

if vim.g.vscode then
  set_keymap('n', 'q', ':<C-u>call VSCodeCall("workbench.action.closeActiveEditor")<CR>',
      { noremap = true, silent = true })
end
