local set_keymap = vim.api.nvim_set_keymap
set_keymap('n', '<CR>', ':<C-u>w<CR>',           { noremap = true, silent = true })
set_keymap('n', 'q', ':q<CR>',                   { noremap = true, silent = true })
set_keymap('n', 'Q', ':qa<CR>',                   { noremap = true, silent = true })
set_keymap('n', '<C-q>', 'q',                    { noremap = true, silent = true })
set_keymap('n', '<C-y>', '<C-v>',                { noremap = true, silent = true })
set_keymap('n', 'U', '<C-r>',                    { noremap = true, silent = true })
set_keymap('n', 'vy', 'ggVG',                    { noremap = true, silent = true })
set_keymap('i', 'jj', '<Esc>',                   { noremap = true, silent = true })
set_keymap('n', 'j', 'gj',                       { noremap = true, silent = true })
set_keymap('n', 'k', 'gk',                       { noremap = true, silent = true })
set_keymap('n', 'H', '^',                        { noremap = true, silent = true })
set_keymap('n', 'L', '$',                        { noremap = true, silent = true })
set_keymap('v', 'H', '^',                        { noremap = true, silent = true })
set_keymap('v', 'L', '$',                        { noremap = true, silent = true })
set_keymap('n', ';', ':',                        { noremap = true, silent = false })
set_keymap('n', ':', 'm',                        { noremap = true, silent = true })
set_keymap('n', 'm', ';',                        { noremap = true, silent = true })
set_keymap('v', ';', ':',                        { noremap = true, silent = true })
set_keymap('v', ':', 'm',                        { noremap = true, silent = true })
set_keymap('v', 'm', ';',                        { noremap = true, silent = true })
set_keymap('n', 'R', '<Plug>(operator-replace)', { noremap = false, silent = true })
set_keymap('v', 'R', '<Plug>(operator-replace)', { noremap = false, silent = true })

set_keymap('', 'w', '<Plug>CamelCaseMotion_w',   { noremap = false, silent = true })
set_keymap('', 'b', '<Plug>CamelCaseMotion_b',   { noremap = false, silent = true })
set_keymap('', 'e', '<Plug>CamelCaseMotion_e',   { noremap = false, silent = true })
set_keymap('', 'ge', '<Plug>CamelCaseMotion_ge', { noremap = false, silent = true })

set_keymap('n', '*', "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>",   { noremap = false, silent = true })
set_keymap('v', '*', "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>",   { noremap = false, silent = true })
set_keymap('n', '#', "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>",   { noremap = false, silent = true })
set_keymap('v', '#', "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>",   { noremap = false, silent = true })
set_keymap('n', 'g*', "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', 'g*', "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('n', 'g#', "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })
set_keymap('v', 'g#', "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>", { noremap = false, silent = true })

set_keymap('n', 'gh', ':<C-u>Octo actions<CR>',         { noremap = true, silent = true })
set_keymap('n', 'gH', ":<C-u>GHInteractive<CR>",        { noremap = true, silent = true })
set_keymap("n", "gl", "<cmd>lua _lazygit_toggle()<CR>", { noremap = true, silent = true })

set_keymap('n', '<C-k>', ':lua vim.lsp.buf.signature_help()<CR>', { noremap = true, silent = true })
set_keymap('n', 'K', ':lua vim.lsp.buf.hover()<CR>',              { noremap = true, silent = true })

set_keymap('n', 'gd', ':lua vim.lsp.buf.definition()<CR>',                               { noremap = true, silent = true })
set_keymap('n', 'gG', ':lua vim.lsp.buf.type_definition()<CR>',                          { noremap = true, silent = true })
set_keymap('n', 'gi', ':lua vim.lsp.buf.implementation()<CR>',                           { noremap = true, silent = true })
set_keymap('n', 'gr', ':lua vim.lsp.buf.references()<CR>',                               { noremap = true, silent = true })
set_keymap('n', 'gs', '<Cmd>lua require"telescope.builtin".lsp_document_symbols{}<CR>',  { noremap = true, silent = true })
set_keymap('n', 'gS', '<Cmd>lua require"telescope.builtin".lsp_workspace_symbols{}<CR>', { noremap = true, silent = true })
set_keymap('n', '<space>g', ':lua vim.lsp.buf.code_action()<CR>',                              { noremap = true, silent = true })
set_keymap('n', '<space>f', ':lua vim.lsp.buf.formatting()<CR>',                         { noremap = true, silent = true })
set_keymap('n', '<space>r', ':lua vim.lsp.buf.rename()<CR>',                                   { noremap = true, silent = true })

set_keymap('n', 'ta', '<Plug>(EasyAlign)',                                               { noremap = false, silent = false })
set_keymap('x', 'ta', '<Plug>(EasyAlign)',                                               { noremap = false, silent = false })
set_keymap('n', 'tb', ':<C-u>Telescope git_branches<CR>',                                { noremap = true,  silent = true })
set_keymap('n', 'tc', ':<C-u>Telescope commands<CR>',                                    { noremap = true,  silent = true })
set_keymap('n', 'tC', ':<C-u>Telescope command_history<CR>',                             { noremap = true,  silent = true })
set_keymap('n', 'td', ':<C-u>DiffviewOpen<CR>',                                          { noremap = true,  silent = true })
set_keymap('n', 'tD', ':<C-u>DiffviewClose<CR>',                                         { noremap = true,  silent = true })
set_keymap('n', 'te', ':<C-u>Telescope buffers<CR>',                                     { noremap = true,  silent = true })
set_keymap('n', 'tf', ':<C-u>Telescope current_buffer_fuzzy_find<CR>',                   { noremap = true,  silent = true })
set_keymap('n', 'tF', ':<C-u>Telescope live_grep<CR>',                                   { noremap = true,  silent = true })
set_keymap('n', 'th', '<cmd>lua require("spectre").open_file_search()<CR>',              { noremap = true,  silent = true })
set_keymap('n', 'tH', '<cmd>lua require("spectre").open()<CR>',                          { noremap = true,  silent = true })
set_keymap('n', 'ti', ':<C-u>Telescope diagnostics<CR>',                                 { noremap = true,  silent = true })
set_keymap('n', 'tI', ':<C-u>TroubleToggle<CR>',                                         { noremap = true,  silent = true })
set_keymap('n', 'tj', ':lua vim.diagnostic.goto_next()<CR>',                             { noremap = true,  silent = true })
set_keymap('n', 'tk', ':lua vim.diagnostic.goto_prev()<CR>',                             { noremap = true,  silent = true })
set_keymap('n', 'tl', ':<C-u>noh<CR>',                                                   { noremap = true,  silent = true })
set_keymap('n', 'tm', ':<C-u>Telescope marks<CR>',                                       { noremap = true,  silent = true })
set_keymap('n', 'tn', ':<C-u>bnext<CR>',                                                 { noremap = true,  silent = true })
set_keymap('n', 'to', ':<C-u>Telescope find_files find_command=fd,-HLE.git,-tf<CR>',     { noremap = true,  silent = true })
set_keymap('n', 'tp', ':<C-u>bprev<CR>',                                                 { noremap = true,  silent = true })
set_keymap('n', 'tr', ':<C-u>Telescope lsp_references<CR>',                              { noremap = true,  silent = true })
set_keymap('n', 'tt', ':<C-u>NeoTreeFloatToggle<CR>',                                    { noremap = true,  silent = true })
set_keymap('n', 'tw', ":<C-u>Bdelete<CR>",                                               { noremap = true,  silent = true })
set_keymap('n', 'ty', ':<C-u>Telescope registers<CR>',                                   { noremap = true,  silent = true })
set_keymap('n', 't;', ':<C-u>CommaOrSemiColon<CR>',                                      { noremap = true,  silent = true });
set_keymap('n', 't?', ':<C-u>Telescope keymaps<CR>',                                     { noremap = true,  silent = true })
set_keymap('n', 't*', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>', { noremap = true,  silent = true })
set_keymap('v', 't*', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>', { noremap = true,  silent = true })
set_keymap('n', 't/', '<Plug>(comment_toggle_linewise_current)',                         { noremap = false, silent = true })
set_keymap('v', 't/', '<Plug>(comment_toggle_blockwise_visual)',                         { noremap = false, silent = true })

if vim.g.vscode then
  set_keymap('n', 'q', ':<C-u>call VSCodeCall("workbench.action.closeActiveEditor")<CR>',
      { noremap = true, silent = true })
end
