#! /usr/bin/zsh

if [ -f /usr/share/zsh-completion/zsh_completion ]; then
  . /usr/share/zsh-completion/zsh_completion
fi

if [ -f ~/.zsh/git-completion.bash ]; then
  fpath=(~/.zsh $fpath)
  zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
  autoload -Uz compinit && compinit
fi

if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  . ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if exists kubectl; then
    compdef k=kubectl
    source <(kubectl completion zsh)
fi
