#! /usr/bin/zsh
#
autoload -Uz compinit && compinit
autoload colors
colors
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

if [ -f /usr/share/zsh-completion/zsh_completion ]; then
  . /usr/share/zsh-completion/zsh_completion
fi

if [ -f ~/.zsh/git-completion.bash ]; then
  fpath=(~/.zsh $fpath)
  zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fi

if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  export ZSH_AUTOSUGGEST_STRATEGY='completion'
  . ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if exists kubectl; then
    . <(kubectl completion zsh)
    compdef k=kubectl
fi
